# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Go Test
on:
  push:
    branches-ignore:
      - temp
  pull_request:
    branches-ignore:
      - temp
defaults:
  run:
    working-directory: ./src
jobs:
  test:
    strategy:
      matrix:
        # [ubuntu-latest, macos-latest, windows-latest]
        platform: [ windows-latest ]
        go-version: [ 1.19.x ]
    runs-on: ${{ matrix.platform }}
    name: Integration tests
    steps:
      - name: Check out code into the Go module directory.
        uses: actions/checkout@v3

      # https://github.com/actions/cache#example-workflow
      # https://github.com/actions/cache/blob/main/examples.md#go---modules
      - name: Enable Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          # path:
          #   Linux: ~/.cache/go-build
          #   MacOS: ~/Library/Caches/go-build
          #   Windows: ~\AppData\Local\go-build
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go.
        if: steps.cache-action.outputs.cache-hit != 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: go mod tidy
        if: steps.cache-action.outputs.cache-hit != 'true'
        run: go mod tidy

      - name: test All
        run: go test ./... -v

      - name: Verify we have our cached file
        run: |
          dir ~\AppData\Local\go-build &&
          dir ~\go\pkg\mod
